CREATE DATABASE XYZ;

USE XYZ;
CREATE TABLE ABC(
ROLLNO INT PRIMARY KEY,
NAME VARCHAR(50),
MARKS INT,
GRADE VARCHAR(1),
CITY VARCHAR(50));
INSERT INTO ABC(rollno, name,marks,grade,city)
values
(101,"anil",78,"C","Pune"),
(102,"Bhumika",93,"A","Mumbai"),
(103,"Chetan",85,"B","Mumbai"),
(104,"Dhruv",96,"A","Delhi"),
(105,"Emaneul",12,"F","Delhi"),
(106,"Farah",82,"B","Delhi");
SELECT * FROM ABC;
SELECT CITY,avg(MARKS) FROM ABC GROUP BY CITY ORDER BY AVG(MARKS) ASC;
SELECT CITY,avg(MARKS) FROM ABC GROUP BY CITY ORDER BY CITY ASC;
SELECT GRADE,COUNT(ROLLNO) FROM ABC GROUP BY GRADE ORDER BY GRADE;
SELECT CITY,COUNT(ROLLNO) FROM ABC GROUP BY city HAVING MAX(MARKS)>90;
